#!/bin/bash

output_models() {
    #-r  raw input - disables interpretion of backslash escapes and line-continuation in the read data
    #-d  <DELIM>   - recognize <DELIM> as data-end, rather than <newline>
    while IFS= read -r -d $'\0' GZ; do
        NAME=$(gzcat "$GZ" | grep -i "^*ModelName" | sed -re 's/.*"(.*)".*/\1/')
        # MODELS[NAME]="$gz"
        echo "$NAME	$GZ"
    done < <(find Printers/PPDs/Contents/Resources -type f -name "*.gz" -print0)
}

install_ppd() {
    SELECTED_GZ=$1
    BASENAME=$(basename "$SELECTED_GZ")
    PPD_TARGET="/Library/Printers/PPDs/Contents/Resources/$BASENAME"

    declare PATHS

    echo "Inspecting $SELECTED_GZ"

    while IFS= read -r -d $'\n' TARGET_PATH; do
        if [[ -f $TARGET_PATH ]]; then
            # echo "Removing $TARGET_PATH"
            rm -vf $TARGET_PATH
        fi
    done < <(gzcat "$SELECTED_GZ" | grep "/Library" | sed -nre 's/.*".*(\/Library.*)".*/\1/p')

    if [[ -f "$PPD_TARGET" ]]; then
        # echo "Removing $PPD_TARGET"
        rm -vf "$PPD_TARGET"
    else
        echo "$PPD_TARGET is not installed"
    fi
}

# If you want to manually set SELECTED_GZ, you can run something like the
# following find command to find the right gz file for your printer.
# You'll need to replace ML-2525W with the model of YOUR printer.
#   find . -type f -name \*.gz | grep "ML-2525W"
SELECTED_GZ="./Printers/PPDs/Contents/Resources/Samsung ML-2525W Series.gz"

# If you don't have FZF, set the variable above and comment out the following line
SELECTED_GZ=$(output_models | fzf -d '	' --with-nth 1 --accept-nth 2)

install_ppd "$SELECTED_GZ"
